"""initial migration

Revision ID: a218a73c148b
Revises: 
Create Date: 2024-09-24 18:58:41.869268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a218a73c148b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('offer_0', sa.Boolean(), nullable=False),
    sa.Column('offer_1', sa.Boolean(), nullable=False),
    sa.Column('offer_2', sa.Boolean(), nullable=False),
    sa.Column('offer_3', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standard_offer')
    # ### end Alembic commands ###
