"""remove id column

Revision ID: abb80e697a1d
Revises: a218a73c148b
Create Date: 2024-09-24 19:49:06.830851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'abb80e697a1d'
down_revision: Union[str, None] = 'a218a73c148b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standard_offer', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_offer', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
